### ISSUE TITLE
Lucee issues with .each() - prefer for loops on large collections

### ISSUE THREAD

**Issue by MordantWastrel** [coldbox-modules/quick#105]
https://luceeserver.atlassian.net/jira/software/c/projects/LDEV/issues/LDEV-2824

Previously: https://luceeserver.atlassian.net/browse/LDEV-2559 (this has some of the background on the issue)

On any sizable loops, probably best to use `for` until this is resolved. If it's only a few items, I doubt it makes a difference, at least post 5.3.6.

**Comment by elpete** [comment]
I've applied this internally.

**Comment by MordantWastrel** [comment]
This has been resolved on the 5.3.7 and 5.3.8 Lucee branches, so now that you've done it you can stop doing it. :)

https://luceeserver.atlassian.net/browse/LDEV-2559 has the update.
