### ISSUE TITLE
ReturningKeyType does not support column != attribute name

### ISSUE THREAD

**Issue by MordantWastrel** [coldbox-modules/quick#110]
In the event you have a primary key whose attribute name does not equal the column name, the `postInsert` on `ReturningKeyType` will try to assign the attribute name instead of the column name:

```
	public void function postInsert( required any entity, required struct result ) {
		arguments.entity
			.keyNames()
			.each( function( keyName ) {
				entity.assignAttribute( keyName, result.query[ keyName ] );
			} );
	}
```

e.g. this primary key:

`property name="questionID" column="id" type="string" sqltype="idstamp";`

will produce this result:

`column [questionID] not found in query, columns are [ID]`

However, the SQL generated for the insert is correct -- it's just the post-insert interceptor to populate the attribute that should check for a column name.

**Comment by MordantWastrel** [comment]
I think all this needs is one change:

`	entity.assignAttribute( keyName, result.query[ entity.retrieveColumnForAlias( keyName ) ] );`

That worked for me, anyway.

**Comment by elpete** [comment]
I think we need to use `keyColumns` instead of `keyNames`.  I'll get this in real quick. :smirk:

**Comment by elpete** [comment]
Fixed in https://github.com/coldbox-modules/quick/releases/tag/v4.1.0
