### ISSUE TITLE
Implement the ability to cascade relationship deletions

### ISSUE THREAD

**Issue by jclausen** [coldbox-modules/quick#114]
One very useful feature of CF ORM is that it can automatically handle the cascading of deletions.  This prevents a ton of boilerplate and method overloads for deletion within the individual components.

I would suggest implementing a new Quick convention for deletion cascades.  Since the relationships are already defined, assembling the delete statement should be relatively straightforward. Example:

```
property name="_cascade";


variables._cascade = [
 "lookup1",
 "childRelationship1",
 "childRelationship2"
]
```

Then, on `delete()`   the pivot relationships for `lookup1` and the sub-table entries for `childRelationship1` and `childRelationship2` would all be deleted when the owning record is deleted.

**Comment by jclausen** [comment]
Alternately, this could be supported in function metadata attributes on the relationship function:

```
function childRelationship1() cascade{
 return hasMany( "child", "FK_parent" );
}
```

**Comment by elpete** [comment]
I don't love the idea of making this part of Quick.  In my opinion, this can be done safer and more performant by using foreign key constraints in a database.  `SchemaBuilder` makes this easy:

```
schema.create( "posts", function( table ) {
    table.increments( "id" );
    table.unsignedInteger( "userId" )
        .references( "id" )
        .onTable( "users" )
        .onDelete( "CASCADE" );
} );
```
