### ISSUE TITLE
belongsToMany .withCount() mixes-and-matches pivot and destination table, can't bind

### ISSUE THREAD

**Issue by MordantWastrel** [coldbox-modules/quick#115]
`qUser` has a `belongsToMany` relationship `families()`:

```
	function families() {
		return belongsToMany(
			relationName = 'qFamily',
			table = 'family_parents',
			foreignPivotKey = 'userID',
			relatedPivotKey = 'familyID',
			parentKey = 'ID',
			relatedKey = 'familyID'
		);
	}
```

Try to use `.withCount()`:

```
	return this.withCount( {
			"families AS familyWaiverNededCount" : (
				( q ) => {
					q.MissingHealthWaiverForToday()
				}
			)
		} );
	}
```

Produces this SQL:

```
(SELECT TOP (1) COUNT(*) FROM [family_parents] WHERE ([family_parents].[userID] = [users].[ID]) AND NOT EXISTS (SELECT 1 FROM [healthAware] WHERE ([families].[familyID] = [healthAware].[familyID]) AND [healthAware].[waiverDate] = {d '2020-08-31'})) AS [familyWaiverNededCount]
```

It correctly uses the pivot table in the `COUNT(*)` but the `WHERE ([families].[familyID]` clause is referencing a table that hasn't been defined (`families`) -- it should use the pivot table, or else re-write the count statement to use `families`, but that seems more complicated.

The desired result can be achieved by using withCount on the intermediary entity (a `hasMany`) along with `whereHas`, so there are workarounds.

**Comment by MordantWastrel** [comment]
Likely the same underlying issue: If we have this relationship on `qUser`:

```
function familyMembersChildren() {
		return hasManyThrough( [ "families", "children" ] );
	}
```

Instead of returning only children belonging to the user's families, it will return all children -- even though `families()` correctly returns only the user's families.

**Comment by elpete** [comment]
I wasn't able to recreate the `belongsToMany` in our simple test cases.  I might need a reproduction from you.

**Comment by MordantWastrel** [comment]
I am no longer able to repro this with the example case in the current release so am closing the issue as resolved!
