### ISSUE TITLE
Please allow both lists and arrays in relationship definitions

### ISSUE THREAD

**Issue by Daemach** [coldbox-modules/quick#118]
This is a bit pedantic, but it would be helpful if signatures were consistent.  Lists are ordered too so they should be able to be used interchangeably with arrays. 

https://www.screencast.com/t/gaE8BETIQSA

**Comment by elpete** [comment]
I probably won't do this.  I have a thing against lists as a first class citizen when arrays do everything lists do and have none of the problems of how to include a `,` or other delimiter inside the list item.

**Comment by Daemach** [comment]
Then why not make everything arrays?  I am just looking for consistency.
It's confusing to have some relationships that require arrays and others
that require lists.

**Comment by Daemach** [comment]
Following up, I do realize that function arguments and an array passed as
an argument are different things.  And the arrays could be of any length.
It's just confusing to have 2 different method signatures.  By accepting
lists for the through functions, you would have to do something like this:
https://helpx.adobe.com/coldfusion/developing-applications/building-blocks-of-coldfusion-applications/writing-and-calling-user-defined-functions/working-with-arguments-and-variables-in-functions.html
(Using the Arguments scope as an array)
