### ISSUE TITLE
Inserting/Updating Decimals on Adobe 2018 and Ms Sql Server

### ISSUE THREAD

**Issue by DavidWard98** [coldbox-modules/quick#147]
When inserting/updating a column with a decimal it is rounded on Adobe 2018 and MS SQL Server.

Steps to re-create : 
1. An environment with Adobe2018 and MS SQL Server (sorry I don't know how to setup a docker container for this)
2. A simple model with a decimal field.
```
component extends="quick.models.BaseEntity" accessors="true"{
    property name="id";
    property name="my_decimal" sqltype="cf_sql_decimal";
}
```
3. A simple test to see if values are rounded after insert.

```
it('Does not round a decimal when inserted', function() {
      var decimal = 10.55
      var number = getInstance('Number');
      number.fill({'my_decimal': decimal})
      number.save()

      expect(number.getMy_Decimal()).toBe(decimal);
      var numberInDB = getInstance('Number').find(number.getID());
      expect(numberInDB.getMy_Decimal()).toBe(decimal);
 });
```

4. When this test is run on Lucee - passes. When run on Adobe 2018 it fails.

I noticed when using queryExecute I need to pass in scale in a parameter otherwise I get the same rounding issue. 
`queryExecute("INSERT INTO my_table ( amount ) VALUES ( :amount )", { value = amount, cfsqltype = 'decimal', scale = '2' } );`

As a work around to the rounding issue I have made some changes to the generateQueryParamStruct() function in BaseEntity.cfc
I just simply added a scale key to the return struct - with some methods to check if scale exists on the entities property. It's kind of hacky as scale is now attached to every query and I would think there is a better way.

Entity : 
```
component extends="quick.models.BaseEntity" accessors="true"{
    property name="id";
    property name="my_decimal" scale="2";
}
```

generateQueryParamStruct() : 
```
return {
     otherstuff,
    "scale" : attributeHasScale( arguments.column ) ? retrieveScaleForAttribute( arguments.column ) : ""
 }
```

**Comment by elpete** [comment]
I think your fix is a good one.  If there is a `scale` or the attribute we will pass that on to the generated query param.
