### ISSUE TITLE
`.update({...})` tries to update identity columns that were not requested for update

### ISSUE THREAD

**Issue by davidAtInleague** [coldbox-modules/quick#171]
using MSSQL grammar

with a model of:
```
component {
    // table is:
    // create table T (p1 int identity, p2 varchar(max));
    property name="p1"; 
    property name="p2";
}
```

the following code:
`someModel.update({p2: someValue})`

sends an update statement like:
```
-- sends p1 and p2, but we didn't ask to update p1
update [table]
set
  p1=?,
  p2=?
where (predicate stuff here)
```

This could be a perf issue (for a model with a lot of properties, why send them all), but is also a failure case when one property is a primary key subject to an IDENTITY constraint. In the above example, `p1` cannot be explicitly set (even to the value it already possesses) and so throws a db error.

**Comment by MordantWastrel** [comment]
I believe Quick won't try to update the value for `variables._key` in an udpate statement, e.g. in this sample,

`variables._key="p1";` should prevent p1 from appearing in any updates.

**Comment by davidAtInleague** [comment]
in the debugging leading to this issue, it is a non-PK column that is subject to the identity constraint, such that `variables._key` is already bound to some other object property.

**Comment by elpete** [comment]
Quick's `save` method (which `update` calls) attempts to save every attribute on the entity.  `update` is a shortcut for `fill` and `save`.  It is not intended to only update the fields passed.  `save` should be thought of more as "save the state of this entity" rather than "update these certain SQL fields".

Is there a bug here or just a performance question?

**Comment by davidAtInleague** [comment]
I think this was solved by adding readonly=true and update=false attrs to the particular non-primary-key-but-still-identity-column attributes. I'll consider this closed.
