### ISSUE TITLE
mssql grammar ignores empty string default

### ISSUE THREAD

**Issue by davidAtInleague** [coldbox-modules/quick#180]
A default of `''` is ignored:
```
// cf
schema.alter('t', (table) => {
    table.addColumn(
       // intentionally non-null
       table.string( "c", 255 ).default('')
    )
});
// sql
ALTER TABLE [t] ADD [c] VARCHAR(255) NOT NULL
```

The generated alter statement, without a default, errors when adding a new column to a non-empty table.

**Comment by elpete** [comment]
Actually, you need two layers of quotes here. 
```
t.string( “c”, 255 ).default( “‘’” );
```
This is because default is basically a RAW value for things like numbers and CURRENT_TIMESTAMP.

**Comment by elpete** [comment]
See https://qb.ortusbooks.com/schema-builder/column-modifiers#default
