### ISSUE TITLE
IDEA: Add `Exclude` Additional Argument to `Fill()` Methods

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/quick#181]
It's great being able to populate a Quick entity using `fill()`, however, it might be handy to have an `exclude` argument option similar to Wirebox's object populator.  That way, users could fill their entities based on the `rc` scope, but exclude any properties they do not want to overwrite.

Here's how you might do it with Wirebox:
```
prc.user = wirebox
    .getObjectPopulator()
    .populateFromStruct(
        target = userService.newEntity();
        memento = rc,
        exclude = "id,secretProperty"  // wirebox will exclude these keys from rc
    );
```

Something similar in Quick would be:
```
prc.user.fill(
	attributes = rc,
	exclude = "id,secretProperty"
);
```

I'll create a simple PR to show how something like this could be accomplished.

**Comment by homestar9** [comment]
PR example:
https://github.com/coldbox-modules/quick/compare/main...homestar9:patch-1

We could also add other arguments that Wirebox has like "include", etc...  This is just an example for simplicity sake.

**Comment by MordantWastrel** [comment]
We do this by combining Quick with cbvalidate.

```
this.constraints = {
    'somePropIWant' : { constraints }
   'someOtherPropI Want' : { constraints }
}
```

then if `rc` has those two plus `somePropIDon'tWant` we do this:

`var validated = validateOrFail( target = rc, constraints = myObj.getConstraints() )` (needs a getter 'cause it's private)

`myObj.fill( validated )`

Any property that doesn't have a corresponding constraint will be removed from `validated`. We also have different constraint getters for different 'modes' of operation when a property might be allowed in a CREATE but not an UPDATE, etc.

**Comment by homestar9** [comment]
@MordantWastrel, that makes sense for cbvalidation users, but you'd also have to validate twice, right?

```
function update( event, rc, prc ) {
	
	// validate rc scope
	validateOrFail(
		target = rc,
		constraints = { constraints }
	)

	// fill entity
	prc.user = getInstance( "User" ).fill(
		attributes = rc
	);

	// Now validate the entity
	validateOrFail( prc.user );

	prc.user.save();

);
```

**Comment by homestar9** [comment]
Now that I think about it more, I think it works best with both the same `include` and `exclude` arguments that Wirebox has.  That way you could dynamically pass in the properties you want to fill or ignore based on something like user permissions.

**Comment by homestar9** [comment]
It looks like this was already proposed back in [May, 2020](https://github.com/coldbox-modules/quick/issues/81).  Here's a PR to add these helper methods:
https://github.com/coldbox-modules/quick/pull/182
