### ISSUE TITLE
Quick does not respect qb's 'returnFormat' setting in coldbox.cfc

### ISSUE THREAD

**Issue by ryanalbrecht** [coldbox-modules/quick#186]
Hi,

In my coldbox.cfc I have the following settings

```	
// quick
quick = {
   defaultGrammar = "MySQLGrammar@qb",
},

// qb
qb = {
   returnFormat: "query"
},
```

If use `.retrieveQuery().get()` on a quick entity, the default return format is not the same as what is set in the coldbox.cfc.

**Comment by elpete** [comment]
Quick maintains it's own qb instance outside of `qb`'s defaults.  This is so it can rely on certain things being true for any queries Quick runs.  One of these things is Quick expects queries to come back as arrays.  If you are wanting to drop down to Quick's internal qb instance and get the result as a query, you are going to need to call `.setReturnFormat( "query" )` on it before executing the query.

This could change in future versions, but it's quite a bit of effort to switch for not too much gain, in my opinion.

**Comment by elpete** [comment]
I would happily accept a PR that handles this, complete with tests.  Otherwise, I probably won't be putting my time towards this.  Thanks for understanding.
