### ISSUE TITLE
[Quick 5.1.0] ApplyGlobalScopes Is Being Ignored By Default

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/quick#191]
It appears that Quick no longer applies global scopes via the  `applyGlobalScopes()` method as it did in Quick 4.  I'm not sure if this is an intentional change, but it feels like a possible bug.

**To replicate the issue:**
Create an entity `Post`
```
component 
    extends="Quick.models.BaseEntity" 
    accessors="true"
    table="post"
{
    
    property name="id";
    property name="name";

    function applyGlobalScopes() {
        this.includeAuthorName()
    }

    // Join with the user table to get some additional data.
    // note: I know you can use relationships. This is just an example.
    function scopeIncludeAuthorName( query ) {
        var sub = query.newQuery()
            .select( [ "user.id", "user.firstName", "user.lastName" ] )
            .from( "user" )
        ;
        query.leftJoinSub( "user", sub, "post.userId", "=", "user.id" );
    } 

}
```

Create a simple handler action like this:
```
function index( event, rc, prc ) {
    prc.post = getInstance( "Post" ).findOrNew( 1 );
    return "done";
}
```    

Examine the query that gets generated, in Quick 4 you will see this:
```
SELECT 
  TOP (1) [post].[id], 
  [post].[name] 
FROM 
  [post] 
  LEFT JOIN (
    SELECT 
      [user].[id], 
      [user].[firstName], 
      [user].[lastName] 
    FROM 
      [user]
  ) AS [user] ON [post].[userId] = [user].[id] 
WHERE 
  ([post].[id] = 1)
```

In Quick 5, you will see this:
```
SELECT 
  TOP (1) [post].[id], 
  [post].[name] 
FROM 
  [post] 
WHERE 
  ([post].[id] = 1)
```

Note the missing join that should have been applied via `applyGlobalScopes()`.

**Workaround:**
Explicitly call the scope in your handler like this:
```
function index( event, rc, prc ) {
    prc.post = getInstance( "Post" ).includeAuthorName().findOrNew( 1 );
    return "done";
}
```
The workaround generates the query as expected:
```
SELECT 
  TOP (1) [post].[id], 
  [post].[name] 
FROM 
  [post] 
  LEFT JOIN (
    SELECT 
      [user].[id], 
      [user].[firstName], 
      [user].[lastName] 
    FROM 
      [user]
  ) AS [user] ON [post].[userId] = [user].[id] 
WHERE 
  ([post].[id] = 1)
```

**What about RetrieveQuery()?**
I'm not sure if this is related or not, but if you call `retrieveQuery().toSql()` in Quick 4 or Quick 5, you will not see the join there either.  It only grabs the basic query unless you explicitly call the scope.
```
writeDump( getInstance( "Post" ).retrieveQuery().toSql() );abort;
```
Returns the following in Quick 4 and Quick 5: 
`SELECT [post].[id], [post].[name] FROM [post]`

```
writeDump( getInstance( "Post" ).includeAuthorName().retrieveQuery().toSql() );abort;
```
Returns the following in Quick 4 and Quick 5:
`SELECT [post].[id], [post].[name] FROM [post] LEFT JOIN (SELECT [user].[id], [user].[firstName], [user].[lastName] FROM [user]) AS [user] ON [post].[userId] = [user].[id]`

**Comment by elpete** [comment]
I noticed this as well today.  In my digging in, I noticed that scopes in the `applyGlobalScopes` method now need to be called on the passed in builder instance.  This was missing from the docs but has now been added. ([link](https://quick.ortusbooks.com/upgrade-guide#applyglobalscopes-functions-now-receive-a-builder-instance-that-should-be-used-to-call-scopes)).

Here's the gist of the new upgrade step:

`applyGlobalScopes` functions now receive a Builder instance that should be used to call scopes
Instead of this:
```cfc
function applyGlobalScopes() {
    this.addVendorName();
    this.addLocationName();
}
```
the scopes should be called on the passed in Builder instance:
```cfc
function applyGlobalScopes( qb ) {
    qb.addVendorName();
    qb.addLocationName();
}
```

Thanks for raising the issue.  Let me know if this fixes it for you as it did for me.

**Comment by homestar9** [comment]
@elpete, yes that fixed the issue on my end as well.  Thank you.

Out of curiosity, was this change part of the performance updates for Quick 5?  It would make sense that offloading some of the function calls to `qb` could make `BaseEntity` a bit leaner.

I'll also be posting some edits to the docs to reflect this change in the next couple of days.
