### ISSUE TITLE
[Quick 9.0.2] Calling Relationship Setter on HasManyDeep (HasManyThrough) Throws Exception 

### ISSUE THREAD

**Issue by homestar9** [coldbox-modules/quick#255]
**Issue:**
Calling relationship setter on a HasManyThrough (HasManyDeep) relationship will throw the exception:
_"Method does not exist on QueryBuilder [applySetter]"_

**How to Replicate:**
1. Define a HasManyThrough relationship:
```
// Page entity 

// a `Page` has many `Category` through intermediate `PageCategory` entities
function categories() {
      return hasManyThrough( [ "pageCategories", "category" ] );
}

function pageCategories() {
        return hasMany( "PageCategory@cms", "pageId" );
}
```

2. Attempt to call the setter in your handler:
```
prc.page.setCategories( "1,2,3" );
```

**Expected:**
I expected the relationship setter to function like the other relationship types and persist the new categories via the `PageCategory` intermediate entity.

**Actual Result:**
Throws exception.

**Workarounds?**
None that I can think of unless you work directly with the intermediate entity relationship, but that creates complexity in your handlers or model, which I believe should be handled by the ORM.

**Comment by homestar9** [comment]
I am still struggling to come up with a workaround. @elpete, do you have any ideas?

**Comment by elpete** [comment]
I don’t currently have plans to implement setters for the `through` or `deep` methods. It would be a lot of work to determine which intermediate entities needed to be created. I would be open to accepting a PR for it provided it had lots of detailed tests. Sorry.

**Comment by homestar9** [comment]
I understand. In the meantime, might I suggest returning a special exception message saying that calling setters for the `through` or `deep` methods is not currently supported? This would be better than the current error message, which makes it look like a method is missing.
