### ISSUE TITLE
UpdateOrInsert cannot cast value correctly

### ISSUE THREAD

**Issue by Tropicalista** [coldbox-modules/quick#75]
I'm using this code:

```
getInstance("Theme@admin")
	.where( 'slug', "prova" )
	.updateOrInsert( { version = "1.3.0", slug = "prova" } )
```
The version field is converted to timestring.

This code:
```
c = getInstance("Theme@admin")
c.setSlug("prova")
c.setVersion("1.3.0")
c.save()
```
works as expected.

Modules Version:

qb: 7.6.0
Quick: 2.5.7

Theme entity code:
```
    property name="id";
    property name="slug";
    property name="name" column="theme_name";
    property name="author";
    property name="authorUri" column="author_uri";
    property name="version" sqltype="cf_sql_varchar";
    property name="themeUri" column="theme_uri";
    property name="description";
    property name="screenshot";
    property name="license";
    property name="tags";
    property name="referralUrl" column="referral_url";
    property name="hits" default="1";
    property name="hasReferral";
    property name="repository";
```

Database:
MySql 10.4.8-MariaDB

**Comment by elpete** [comment]
Could you provide the following, please:

1. Version of Quick and qb 
2. `Theme` entity code (can put in a `<details>` tag in your comment)
3. Database type and version

Thanks!

**Comment by Tropicalista** [comment]
Issue updated :)

**Comment by elpete** [comment]
Any chance you could test this using `quick@3.0.0-beta`? I believe this was fixed there.

**Comment by Tropicalista** [comment]
Yes, with latest works great.

**Comment by Tropicalista** [comment]
This should be reopened because it works only if using save() method. With UpdateOrInsert() still convert to timestring.

**Comment by elpete** [comment]
Sorry, I guess I misunderstood.  So `updateOrInsert` doesn't use the correct `sqltype` on the `3.0.0-beta` either?

**Comment by Tropicalista** [comment]
That's correct.

Using save method is working.
Using UpdateOrInsert() still save a string "2.1.0" as a date

**Comment by elpete** [comment]
Just curious, can you try the new [`updateOrCreate`](https://quick.ortusbooks.com/v/3.0.0/guide-1/getting-started/updating-existing-entities#updateorcreate) method in `quick@3.0.0-beta`?

If that works, I may need an alias for `updateOrInsert` for Quick so your code works as well.

**Comment by Tropicalista** [comment]
What do you mean by `quick@3.0.0-beta`?
Commandbox only give me quick@3.0.0-beta.1 to 3.0.0-beta.6

I have tried with all, same results. But I was thinking, can be a database settings misconfiguration?
Are you able to replicate the error?

I have checked the code and if I dump the runquery I see this 

![screenshot-127 0 0 1_58609-2020 04 29-22_38_11](https://user-images.githubusercontent.com/1663035/80644691-5a0a1c80-8a6a-11ea-979f-6fea864b0ef6.png)

It seems that params are passed correctly, but the query is wrong. Not sure what's happening here.

**Comment by Tropicalista** [comment]
I think the bug is in [qb](https://github.com/coldbox-modules/qb/blob/master/models/Query/QueryUtils.cfc#L59) infersql.

`isDate('1.2.3')` is true.

**Comment by elpete** [comment]
Technically, it could be a date, so that code isn’t a bug even if the behavior here is incorrect. In Quick, though, the sqltype should be applied which skips the `inferSQLType` call, so that’s what I’m trying to narrow down. Thanks for the leg work.

**Comment by Tropicalista** [comment]
I also taught the sqltype would be applied. I was just asking why it's not applied.
If I can give you an input, I suppose the `where` clause is messing up things, because if I dump on `generateQueryParamStruct()` function the only check is for the property inserted in the where clause.

**Comment by elpete** [comment]
NOTE: All of the following is true of Quick 3.0.0.

The Quick way to do this is with the [`updateOrCreate`](https://quick.ortusbooks.com/v/3.0.0/guide-1/getting-started/creating-new-entities#updateorcreate) call, like so:
```cfc
getInstance( "Theme" )
    .updateOrCreate(
        { "slug": "prova" },
        { "version": "1.3." }
    );
```

In `quick@3.0.0-beta.8` I have also forwarded on `updateOrInsert` calls on the entity to `updateOrCreate`, so your above code will work.
