### ISSUE TITLE
_variables but not _functions()

### ISSUE THREAD

**Issue by MordantWastrel** [coldbox-modules/quick#78]
Early on in Quick's development, variables like `key` were renamed to `_key` to avoid conflict with user-defined properties and functions. 

But the functions referring to those values do not have the underscore, so if I have a business object of type `Entity` with a field `entityName` then it breaks.

May I submit a PR replacing `entityName` with `_entityName()` and likewise with `mappingName` and `tableName`?

**Comment by elpete** [comment]
I’m not opposed to this change in general. It does make me wonder how far we go in this change. Is every method prefixed with an underscore? What if someone wants an underscore in their method name? I’d like to get some good boundaries set up. 

Additionally, this is, unfortunately, a breaking change. I know I personally have code that uses the `entityName` function outside of Quick itself. 

I wonder if there is some way we could proxy method calls if and when the need arises.

**Comment by MordantWastrel** [comment]
I don't propose changing the boundaries -- just enforcing the ones you already have.

If the convention is that `_method()` is internal, and I really want to have a `_method()` on my entity that conflicts with what's there, I think you can say 'tough luck,' and in fact you could say that to me now since I'm almost certainly the only person on Earth who both a) uses Quick and b) has an entity management solution using Quick to run into this problem. :) 

So if you'd rather not deal with it, you can kick this back and we'll change our code in one place so that you (and others) don't have to deal with it; it's more just a question of whether it's the 'right thing to do'.

**Comment by MordantWastrel** [comment]
We just changed our property not to be `entityName` so if you don't want to open this can of worms, we're no longer affected by it.

**Comment by elpete** [comment]
I think we'll punt on this one for now.
