### ISSUE TITLE
applyColumnFormatter is prepending [table] to [column]

### ISSUE THREAD

**Issue by MordantWastrel** [coldbox-modules/quick#79]
When QB calls `returning( 'primayKeyColumn' )`,  the value that gets saved to the QB's returning instance is `tableName.columnName` (which matches the value that gets saved to the columns property) but the resulting SQL is: `OUTPUT INSERTED.[tableName].[columnName]`,  which isn't valid.

At least on MSSQL, the table name should not be presented in an INSERTED statement. As a workaround, removing `applyColumnFormatter` from `returning()` solved this.

**Comment by elpete** [comment]
Hmmm...I think this may be a qb fix. Should returning always strip away a table if it has one? We can’t skip calling the column formatted altogether in case there is an alias being returned.

**Comment by MordantWastrel** [comment]
For MSSQL, it should always strip a table name for OUTPUT INSERTED.

**Comment by elpete** [comment]
Fixed in qb 7.9.2
