### ISSUE TITLE
Add wirebox populator helpers to Quick

### ISSUE THREAD

**Issue by MordantWastrel** [coldbox-modules/quick#81]
https://wirebox.ortusbooks.com/advanced-topics/wirebox-object-populator/populatefromstruct

Whether or not we add these to `.fill()` or add a new method, it'd be nice to support `include` and `exclude`, `ignoreEmpty`, `nullEmptyInclude` and `nullEmptyExclude`. `composeRelationships` is a bit ambitious (for now) but presumably would also be pretty neat.

**Comment by homestar9** [comment]
Created PR: https://github.com/coldbox-modules/quick/pull/182
